version: '3'

services:
  postgres:
    image: postgres:13
    container_name: currencybot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currencybot
    volumes:
      - .testbot/data/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
